#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finalproj
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="mainbasedata")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertuser(user instance);
    partial void Updateuser(user instance);
    partial void Deleteuser(user instance);
    partial void Insertcust(cust instance);
    partial void Updatecust(cust instance);
    partial void Deletecust(cust instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Finalproj.Properties.Settings.Default.mainbasedataConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<user> users
		{
			get
			{
				return this.GetTable<user>();
			}
		}
		
		public System.Data.Linq.Table<cust> custs
		{
			get
			{
				return this.GetTable<cust>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[user]")]
	public partial class user : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _NO;
		
		private string _BRAND;
		
		private string _TYPE;
		
		private string _MODEL;
		
		private int _PRICE;
		
		private int _QUANTITY;
		
		private string _IMAGE;
		
		private string _DETAILS;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNOChanging(int value);
    partial void OnNOChanged();
    partial void OnBRANDChanging(string value);
    partial void OnBRANDChanged();
    partial void OnTYPEChanging(string value);
    partial void OnTYPEChanged();
    partial void OnMODELChanging(string value);
    partial void OnMODELChanged();
    partial void OnPRICEChanging(int value);
    partial void OnPRICEChanged();
    partial void OnQUANTITYChanging(int value);
    partial void OnQUANTITYChanged();
    partial void OnIMAGEChanging(string value);
    partial void OnIMAGEChanged();
    partial void OnDETAILSChanging(string value);
    partial void OnDETAILSChanged();
    #endregion
		
		public user()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int NO
		{
			get
			{
				return this._NO;
			}
			set
			{
				if ((this._NO != value))
				{
					this.OnNOChanging(value);
					this.SendPropertyChanging();
					this._NO = value;
					this.SendPropertyChanged("NO");
					this.OnNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRAND", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string BRAND
		{
			get
			{
				return this._BRAND;
			}
			set
			{
				if ((this._BRAND != value))
				{
					this.OnBRANDChanging(value);
					this.SendPropertyChanging();
					this._BRAND = value;
					this.SendPropertyChanged("BRAND");
					this.OnBRANDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string TYPE
		{
			get
			{
				return this._TYPE;
			}
			set
			{
				if ((this._TYPE != value))
				{
					this.OnTYPEChanging(value);
					this.SendPropertyChanging();
					this._TYPE = value;
					this.SendPropertyChanged("TYPE");
					this.OnTYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODEL", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MODEL
		{
			get
			{
				return this._MODEL;
			}
			set
			{
				if ((this._MODEL != value))
				{
					this.OnMODELChanging(value);
					this.SendPropertyChanging();
					this._MODEL = value;
					this.SendPropertyChanged("MODEL");
					this.OnMODELChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRICE", DbType="Int NOT NULL")]
		public int PRICE
		{
			get
			{
				return this._PRICE;
			}
			set
			{
				if ((this._PRICE != value))
				{
					this.OnPRICEChanging(value);
					this.SendPropertyChanging();
					this._PRICE = value;
					this.SendPropertyChanged("PRICE");
					this.OnPRICEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUANTITY", DbType="Int NOT NULL")]
		public int QUANTITY
		{
			get
			{
				return this._QUANTITY;
			}
			set
			{
				if ((this._QUANTITY != value))
				{
					this.OnQUANTITYChanging(value);
					this.SendPropertyChanging();
					this._QUANTITY = value;
					this.SendPropertyChanged("QUANTITY");
					this.OnQUANTITYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IMAGE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string IMAGE
		{
			get
			{
				return this._IMAGE;
			}
			set
			{
				if ((this._IMAGE != value))
				{
					this.OnIMAGEChanging(value);
					this.SendPropertyChanging();
					this._IMAGE = value;
					this.SendPropertyChanged("IMAGE");
					this.OnIMAGEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DETAILS", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string DETAILS
		{
			get
			{
				return this._DETAILS;
			}
			set
			{
				if ((this._DETAILS != value))
				{
					this.OnDETAILSChanging(value);
					this.SendPropertyChanging();
					this._DETAILS = value;
					this.SendPropertyChanged("DETAILS");
					this.OnDETAILSChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.cust")]
	public partial class cust : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Serial;
		
		private string _FULL_NAME;
		
		private string _ADDRESS;
		
		private string _PHONE_NO;
		
		private string _MAIL;
		
		private string _BLOOD_GROUP;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSerialChanging(int value);
    partial void OnSerialChanged();
    partial void OnFULL_NAMEChanging(string value);
    partial void OnFULL_NAMEChanged();
    partial void OnADDRESSChanging(string value);
    partial void OnADDRESSChanged();
    partial void OnPHONE_NOChanging(string value);
    partial void OnPHONE_NOChanged();
    partial void OnMAILChanging(string value);
    partial void OnMAILChanged();
    partial void OnBLOOD_GROUPChanging(string value);
    partial void OnBLOOD_GROUPChanged();
    #endregion
		
		public cust()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Serial", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Serial
		{
			get
			{
				return this._Serial;
			}
			set
			{
				if ((this._Serial != value))
				{
					this.OnSerialChanging(value);
					this.SendPropertyChanging();
					this._Serial = value;
					this.SendPropertyChanged("Serial");
					this.OnSerialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[FULL NAME]", Storage="_FULL_NAME", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string FULL_NAME
		{
			get
			{
				return this._FULL_NAME;
			}
			set
			{
				if ((this._FULL_NAME != value))
				{
					this.OnFULL_NAMEChanging(value);
					this.SendPropertyChanging();
					this._FULL_NAME = value;
					this.SendPropertyChanged("FULL_NAME");
					this.OnFULL_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDRESS", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string ADDRESS
		{
			get
			{
				return this._ADDRESS;
			}
			set
			{
				if ((this._ADDRESS != value))
				{
					this.OnADDRESSChanging(value);
					this.SendPropertyChanging();
					this._ADDRESS = value;
					this.SendPropertyChanged("ADDRESS");
					this.OnADDRESSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[PHONE NO]", Storage="_PHONE_NO", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PHONE_NO
		{
			get
			{
				return this._PHONE_NO;
			}
			set
			{
				if ((this._PHONE_NO != value))
				{
					this.OnPHONE_NOChanging(value);
					this.SendPropertyChanging();
					this._PHONE_NO = value;
					this.SendPropertyChanged("PHONE_NO");
					this.OnPHONE_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAIL", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MAIL
		{
			get
			{
				return this._MAIL;
			}
			set
			{
				if ((this._MAIL != value))
				{
					this.OnMAILChanging(value);
					this.SendPropertyChanging();
					this._MAIL = value;
					this.SendPropertyChanged("MAIL");
					this.OnMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[BLOOD GROUP]", Storage="_BLOOD_GROUP", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string BLOOD_GROUP
		{
			get
			{
				return this._BLOOD_GROUP;
			}
			set
			{
				if ((this._BLOOD_GROUP != value))
				{
					this.OnBLOOD_GROUPChanging(value);
					this.SendPropertyChanging();
					this._BLOOD_GROUP = value;
					this.SendPropertyChanged("BLOOD_GROUP");
					this.OnBLOOD_GROUPChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
